WordPress documentation
kanopi/Engineering-Best-Practices pull request #24
Opened 2023-02-22 22:42 UTC by kmwalsh

## Description
Adding some starter WordPress documentation.

## Affected URL
http://127.0.0.1:4000/Engineering-Best-Practices/wordpress/#top

## Related Tickets
n/a

## Steps to Validate
1. Pull branch
2. Run github thingy locally
3. 📖 R E A D 📖

2023-07-04 22:03 UTC, wakingmorning commented on _includes/markdown/WordPress.md
> +* Local username/password on all projects should be `kadmin`/`kadmin`. Make it so when you see it otherwise.
Should we publicly post the local credentials for our client sites? 
Let's state something like

"see our password vault for local username/password for all projects.  Make it so..." 

We can add a note in 1password for Local WordPress Environments.

2023-07-04 22:04 UTC, wakingmorning requested changes
One small change.
Thanks for getting these together @kmwalsh 
Moving forward can you assign any PRs to me?
This way, nothing gets missed.

2023-08-28 13:18 UTC, sofiakanopi commented on _includes/markdown/WordPress.md
> +* Local username/password on all projects should be `kadmin`/`kadmin`. Make it so when you see it otherwise.
@kmwalsh tagging you to make sure you saw this comment.

2023-09-05 17:23 UTC, kmwalsh commented
@sofiakanopi @wakingmorning -- all set and merge conflicts resolved. Thank you, sorry I missed this.

2023-09-05 17:28 UTC, kmwalsh commented
Committing helps. ☠️ All set.

2023-09-05 17:30 UTC, sofiakanopi requested changes
One last little thing :)

2023-09-05 17:30 UTC, sofiakanopi commented on _includes/_sass/components/_template-header.scss
> +.header-wordpress,
@kmwalsh to avoid having to edit the CSS each time we add a new page, can we add a generic class to all the pages instead and call it here?

2023-09-05 18:22 UTC, kmwalsh commented on _includes/_sass/components/_template-header.scss
> +.header-wordpress,
Updated!

2023-09-05 18:25 UTC, sofiakanopi requested changes

2023-09-05 18:25 UTC, sofiakanopi commented on _includes/_sass/components/_template-header.scss
> +	background-image: url("img/page-header.png");
So fast! Could you just move that line before line #2 so that the background CSS lives together? I also think you can remove line #2 because `background-size: cover;` is very much supported.

2023-09-05 18:39 UTC, kmwalsh commented on _includes/_sass/components/_template-header.scss
> +	background-image: url("img/page-header.png");
Updated!

2023-09-05 19:55 UTC, sofiakanopi approved these changes

2023-09-05 19:55 UTC, sofiakanopi commented
Thanks @kmwalsh! Approved :)

2023-09-05 20:55 UTC, merged